Update for cisagov move
cisagov/ansible-role-ncats-webd pull request #9
Opened 2020-06-30 14:17 UTC by hillaryj

Update URLs for move to `cisagov` org and remove unnecessary oauth url

## 🗣 Description

- Updates target URL for the move to the `cisagov` org
- Removes oauth from URL query to retrieve tarball since it's now a public repo

## 💭 Motivation and Context

Associated with https://github.com/cisagov/ansible-role-cyhy-core/issues/10 - removes deprecated oauth usage both due to deprecation as well as now the target is publicly accessible without an auth token.

## 🧪 Testing

## 📷 Screenshots (if appropriate)

## 🚥 Types of Changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (causes existing functionality to change)

## ✅ Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2020-07-01 13:05 UTC, jsf9k requested changes
*Once #10 is merged into develop and pulled into this PR*, you still need to:
* Remove `defaults/main.yml`.
* Remove `/github/oauth_token` from `ssm_parameters` in `terraform/iam_user.tf`.
* Run `terraform apply` in the `terraform` directory.

2020-07-02 16:33 UTC, hillaryj commented
Changes have been made and the (targeted) terraform apply is complete!

2020-07-02 17:37 UTC, jsf9k approved these changes
Simplification!  I love it!

2020-07-02 17:47 UTC, mcdonnnj approved these changes
![image](https://user-images.githubusercontent.com/50747025/86393128-958fb580-bc6a-11ea-9a1b-06aacb470101.png)

2020-07-02 17:57 UTC, merged